import type { Club } from '@/types'

// Lista de clubes demo. En producción vendría de Supabase tabla `clubs`.
export const demoClubs: (Club & { referral_code: string; first_payment_at: string; successful_referrals: number; has_shop_addon?: boolean })[] = [
  {
    id: 'club-banfield-rm',
    name: 'Filial Banfield Ramos Mejía',
    slug: 'banfield-rm',
    short_name: 'Banfield RM',
    logo_url: '/escudo-banfield.png',
    primary_color: '#00843D',
    secondary_color: '#C9A84C',
    city: 'Ramos Mejía',
    is_active: true,
    plan: 'pro',
    default_sport_code: 'football_11',
    total_socios: 450,
    created_at: '2025-03-01',
    referral_code: 'BANFIELD-RM-A3X',
    first_payment_at: '2026-03-15', // ~50 días atrás → ya activo
    successful_referrals: 2,
    has_shop_addon: true, // Banfield tiene tienda activa
  },
  {
    id: 'club-brisas',
    name: 'Club Brisas de Haedo',
    slug: 'brisas',
    short_name: 'Brisas',
    logo_url: null,
    primary_color: '#7c3aed',
    secondary_color: '#fbbf24',
    city: 'Haedo',
    is_active: true,
    plan: 'pro',
    default_sport_code: 'baby_5',
    total_socios: 875,
    created_at: '2025-01-15',
    referral_code: 'BRISAS-HD-K7M',
    first_payment_at: '2025-02-01', // muy antiguo
    successful_referrals: 5,
    has_shop_addon: true, // Brisas tiene tienda activa (es Pro + addon)
  },
  {
    id: 'club-boca-rm',
    name: 'Filial Boca Ramos Mejía',
    slug: 'boca-rm',
    short_name: 'Boca RM',
    logo_url: null,
    primary_color: '#0a4ca8',
    secondary_color: '#fbbf24',
    city: 'Ramos Mejía',
    is_active: true,
    plan: 'club',
    default_sport_code: 'football_11',
    total_socios: 312,
    created_at: '2026-02-10',
    referral_code: 'BOCA-RM-Q2P',
    first_payment_at: '2026-04-25', // ~12 días atrás → todavía no activo, falta llegar a 15d
    successful_referrals: 0,
  },
  // ──────────────────────────────────────────────────────────────────────
  // Clubes ficticios por deporte para grabación de pantalla del demo
  // ──────────────────────────────────────────────────────────────────────
  {
    id: 'club-pequenas-estrellas',
    name: 'Escuela Pequeñas Estrellas',
    slug: 'pequenas-estrellas',
    short_name: 'Pequeñas Estrellas',
    logo_url: null,
    primary_color: '#f59e0b',
    secondary_color: '#1e40af',
    city: 'Lanús',
    is_active: true,
    plan: 'club',
    default_sport_code: 'baby_6',
    total_socios: 95,
    created_at: '2026-01-10',
    referral_code: 'PE-LN-B6X',
    first_payment_at: '2026-02-01',
    successful_referrals: 1,
  },
  {
    id: 'club-san-marcos',
    name: 'Club Atlético San Marcos',
    slug: 'san-marcos',
    short_name: 'San Marcos',
    logo_url: null,
    primary_color: '#1d4ed8',
    secondary_color: '#ffffff',
    city: 'Vicente López',
    is_active: true,
    plan: 'pro',
    default_sport_code: 'futsal',
    total_socios: 220,
    created_at: '2025-09-15',
    referral_code: 'CASM-VL-F5T',
    first_payment_at: '2025-10-01',
    successful_referrals: 3,
  },
  {
    id: 'club-las-halcones',
    name: 'Club Las Halcones Hockey',
    slug: 'las-halcones',
    short_name: 'Las Halcones',
    logo_url: null,
    primary_color: '#be123c',
    secondary_color: '#000000',
    city: 'San Isidro',
    is_active: true,
    plan: 'pro',
    default_sport_code: 'hockey_field',
    total_socios: 180,
    created_at: '2025-11-01',
    referral_code: 'LH-SI-HKY',
    first_payment_at: '2025-12-01',
    successful_referrals: 2,
    has_shop_addon: true,
  },
  {
    id: 'club-voley-ituzaingo',
    name: 'Club Vóley Ituzaingó',
    slug: 'voley-ituzaingo',
    short_name: 'Vóley Ituzaingó',
    logo_url: null,
    primary_color: '#16a34a',
    secondary_color: '#fbbf24',
    city: 'Ituzaingó',
    is_active: true,
    plan: 'club',
    default_sport_code: 'volleyball',
    total_socios: 140,
    created_at: '2026-02-20',
    referral_code: 'VI-IZ-VLY',
    first_payment_at: '2026-03-05',
    successful_referrals: 0,
  },
  {
    id: 'club-baskets-quilmes',
    name: 'Báskets Quilmes',
    slug: 'baskets-quilmes',
    short_name: 'Báskets QM',
    logo_url: null,
    primary_color: '#ea580c',
    secondary_color: '#1e3a8a',
    city: 'Quilmes',
    is_active: true,
    plan: 'pro',
    default_sport_code: 'basketball',
    total_socios: 195,
    created_at: '2025-08-10',
    referral_code: 'BQ-QM-BSK',
    first_payment_at: '2025-09-01',
    successful_referrals: 4,
  },
  {
    id: 'club-tigres-rugby',
    name: 'Tigres Rugby Seven',
    slug: 'tigres-rugby',
    short_name: 'Tigres Rugby',
    logo_url: null,
    primary_color: '#000000',
    secondary_color: '#f97316',
    city: 'Pilar',
    is_active: true,
    plan: 'club',
    default_sport_code: 'rugby_7',
    total_socios: 110,
    created_at: '2026-03-01',
    referral_code: 'TR7-PL-RGB',
    first_payment_at: '2026-04-01',
    successful_referrals: 0,
  },
  {
    id: 'club-lobos-rugby',
    name: 'Lobos Rugby Club',
    slug: 'lobos-rugby',
    short_name: 'Lobos Rugby',
    logo_url: null,
    primary_color: '#7c2d12',
    secondary_color: '#fef3c7',
    city: 'Tandil',
    is_active: true,
    plan: 'pro',
    default_sport_code: 'rugby_15',
    total_socios: 280,
    created_at: '2025-07-01',
    referral_code: 'LR15-TD-RGB',
    first_payment_at: '2025-08-15',
    successful_referrals: 6,
    has_shop_addon: true,
  },
  {
    id: 'club-handball-norte',
    name: 'Club Handball Norte',
    slug: 'handball-norte',
    short_name: 'Handball Norte',
    logo_url: null,
    primary_color: '#0891b2',
    secondary_color: '#fef08a',
    city: 'San Fernando',
    is_active: true,
    plan: 'club',
    default_sport_code: 'handball_7',
    total_socios: 130,
    created_at: '2026-01-25',
    referral_code: 'HN-SF-HBL',
    first_payment_at: '2026-02-15',
    successful_referrals: 1,
  },
]

const CURRENT_CLUB_KEY = 'banfieldrm_current_club_id'

export function getCurrentClub(): Club {
  if (typeof window === 'undefined') return demoClubs[0]
  const id = localStorage.getItem(CURRENT_CLUB_KEY)
  return demoClubs.find(c => c.id === id) ?? demoClubs[0]
}

export function setCurrentClub(clubId: string) {
  if (typeof window === 'undefined') return
  localStorage.setItem(CURRENT_CLUB_KEY, clubId)
  // Recargar para que se apliquen los datos del nuevo club
  window.location.reload()
}
